Выполнил разметку
htmlacademy-htmlcss/1350493-nerds-29 pull request #2
Opened 2020-09-13 20:56 UTC by buxpob

2020-09-14 19:24 UTC, costigans requested changes

2020-09-14 19:24 UTC, costigans commented on blank.html
> +<!DOCTYPE html>
Лишний файл

2020-09-14 19:24 UTC, costigans commented on index.html
> +				<img src="#" alt="Логотип интернет магазина «Nerds»">
Нехватает аттрибутов `width` и `height`

2020-09-14 19:24 UTC, costigans commented on index.html
> +				<li><a href="blank.html">Клиенты</a></li>
Вместо «пустой» страницы удобно использовать «заглушки» — `href="#"`

2020-09-14 19:24 UTC, costigans commented on index.html
> +				<li><button type="button"></button></li>
А что это за кнопки? Без текста совсем непонятно :)
_Спойлер_: мы потом спрячем этот текст

2020-09-14 19:24 UTC, costigans commented on index.html
> +					<button type="button">Заказать</button>
Какое действие будет при нажатии на этот элемент?

2020-09-14 19:24 UTC, costigans commented on index.html
> +					<p>Мир никогда не будет прежним<br>
Здесь и в соседних элементах `<br>` лишний — перенос текста будет автоматический, за счёт ширины блока

2020-09-14 19:24 UTC, costigans commented on index.html
> +				<p>Мы — маленькая, но гордая<br>
Лишний `<br>`.
Пройдись по документу и убери все _лишние_ `<br>`

2020-09-14 19:24 UTC, costigans commented on index.html
> +				<!-- или лучше сделать таблицей? -->
Можно, например, использовать `dl/dt`

2020-09-14 19:24 UTC, costigans commented on index.html
> +			<aside>
Что говорится в спецификации? Для чего используется `aside`?

2020-09-14 19:24 UTC, costigans commented on index.html
> +				<li><a href="blank.html">hyml academy</a></li>
Опечатка.
Пиши с заглавной буквы.

2020-09-14 19:24 UTC, costigans commented on index.html
> +				<li><a href="blank.html">mishka</a></li>
Пиши с заглавной буквы.

2020-09-14 19:24 UTC, costigans commented on index.html
> +				<!-- не совсем понятно по ТЗ, это должна быть кнопка или ссылка -->
> 4.2. Клик по кнопке «Напишите нам» открывает модальное окно с формой обратной связи.

2020-09-14 19:24 UTC, costigans commented on index.html
> +			<h2>Давайте дружить, это выгодно!</h2>
Не заголовок, хоть и выглядит похоже

2020-09-14 19:24 UTC, costigans commented on index.html
> +		<!-- не понятно по ТЗ как будет выглядеть -попап, поле для ввода имени и поле для текста?-->
Скопируй макет и отобрази скрытые слои :)

2020-09-14 19:24 UTC, costigans commented on catalog.html
> +	<title>HTML Academy: «Nerds»</title>
В `title` принято отображать название страницы, чтобы можно было отличить страницы сайта открытые в нескольких вкладках

2020-09-14 19:24 UTC, costigans commented on catalog.html
> +	<<footer>
Лишняя скобка

2020-09-15 18:24 UTC, costigans requested changes

2020-09-15 18:24 UTC, costigans commented on catalog.html
>  			<a>
Эта ссылка куда ведёт?

2020-09-15 18:24 UTC, costigans commented on index.html
> +	<title>Интернет магазин «Nerds»</title>
Сейчас у тебя одинаковый `title` у разных страниц.

2020-09-15 18:24 UTC, costigans commented on index.html
> +				<!-- в лекции говорили, что можно использовать вместо заглушки # пустую страницу blank, собственно поэтому и сделал так изначально -->
Да, но символ `#` проще, и можно без «неприятностей» кликать по ссылкам.

2020-09-15 18:24 UTC, costigans commented on index.html
>  			<p>Математически выверенный  дизайн<br>
А что здесь оставил`<br>`?

2020-09-15 18:24 UTC, costigans commented on index.html
> +				<li><button type="button">Слайд 3</button></li>
Отлично!

2020-09-15 18:24 UTC, costigans commented on index.html
> +					<!--Это могла бы быть кнопка, отправляющая в корзину товар, но товар слишком специфичный, для ссылки тоже вроде не подходит, возможно кнопка, которая вызывающая попап?-->
А где здесь товар?
Почему не подходит для ссылки?

2020-09-15 18:24 UTC, costigans commented on index.html
>  					<p>Вы даже не подозреваете,<br>
Для чего оставил <br>?

2020-09-15 18:24 UTC, costigans commented on index.html
> +				<li><a href="#">mishka</a></li>
Поправь названия компаний. Почему всё набрано в нижнем регистре?

2020-09-15 18:24 UTC, costigans commented on index.html
>  				<p>191186, Санкт-Петербург,<br>
Для чего оставил <br>?

2020-09-15 18:24 UTC, costigans commented on index.html
> +			<p>Давайте дружить, это выгодно!<br>
Для чего оставил <br>?
Это могут быть два параграфа?

2020-09-15 18:25 UTC, costigans commented
Валидатор никаких ошибок не выдавал?

2020-09-16 12:21 UTC, costigans approved these changes
Ты можешь отвечать на мои комментарии прямо здесь, на гитхабе, или писать в ТГ.
Общение через комментарии в коде не самый удобный способ :)

2020-09-16 12:21 UTC, costigans commented on catalog.html
> +			<button type="button">Вверх</button>
А могу ли эти «кнопки» быть ссылками? В каких случаях?

2020-09-16 12:21 UTC, costigans commented on catalog.html
> +			</ul>
Удали, лучше не оставлять в разметке ничего, что сейчас не используется.

2020-09-16 12:21 UTC, costigans commented on index.html
> +				<h2>Процентные показатели</h2>
Можно подобрать более «человечный» заголовок. Сейчас канцеляризм какой-то :)

2020-09-16 12:21 UTC, costigans commented on index.html
> +				<li><a href="#">Html academy</a></li>
HTML Academy

2020-09-16 12:21 UTC, costigans commented on index.html
> +				<p>191186, Санкт-Петербург, ул. Б. Конюшенная, д. 19/8</p>
А существует ли какой-то специальный тег для разметки адреса?

2020-09-16 12:21 UTC, costigans commented on index.html
>  				<p>тел. +7 (812) 275-75-75</p>
А что в ТЗ написано про номера телефонов?

2020-09-16 12:21 UTC, merged

2020-09-16 14:39 UTC, buxpob commented on catalog.html
> +			<button type="button">Вверх</button>
Ну обычно, на сайтах, при выборе данных в фильтре, гостя не перекидывает на другую страницу, а обновляется эта страница. Наверно можно сделать ссылками, если так захочет заказчик, но придётся наверно миллион страниц тогда делать под каждую категорию. Если нет, то в каких случаях я не знаю

2020-09-16 14:39 UTC, buxpob commented on index.html
> +				<h2>Процентные показатели</h2>
"Наши показатели" подойдёт?

2020-09-16 14:39 UTC, buxpob commented on index.html
> +				<li><a href="#">Html academy</a></li>
Понял))

2020-09-16 14:39 UTC, buxpob commented on catalog.html
> +			</ul>
хорошо))

2020-09-16 14:39 UTC, buxpob commented on index.html
> +				<p>191186, Санкт-Петербург, ул. Б. Конюшенная, д. 19/8</p>
я бы предположил, что это тег address, но он же используется для контактных данных автора документа, вроде

2020-09-16 14:39 UTC, buxpob commented on index.html
>  				<p>тел. +7 (812) 275-75-75</p>
ещё раз прочитал, ничего, и в гайде никаких интерактивных особенностей нет. Сделать ссылкой?