Выполнил стилизацию главной страницы
htmlacademy-htmlcss/1350493-nerds-29 pull request #3
Opened 2020-09-18 19:43 UTC by buxpob

2020-09-21 06:38 UTC, costigans requested changes

2020-09-21 06:38 UTC, costigans commented on index.html
> +<body class="page-bady">
`page-body`

2020-09-21 06:38 UTC, costigans commented on index.html
> +				<li class="service__item">
Сейчас твои классы похожи на БЭМ-нейминг, но не являются им, и это вводит в заблуждение.
Концепция БЭМ не самая простая тема, готов сейчас обойтись без неё? Поводов запутаться у нас будет достаточно :)

2020-09-21 06:38 UTC, costigans commented on index.html
> +					<li class="indicators-list__item">
Ты используешь разные классы на одинаковые элементы.
`indicators__item/indicators-list__item`

2020-09-21 06:38 UTC, costigans commented on index.html
> +						<p class="indicators__info">50<span class="indicators-item__info_little">%</span></p>
Нет необходимости в классе `.indicators-item__info_little`
Те же самые свойства можно задать селектору `.indicators__info span`
Нужно стараться делать прозе и не усложнять без надобности.

2020-09-21 06:38 UTC, costigans commented on index.html
> +				<li><a class="manufacturers__link" href="#">Mishka</a><img src="#" alt="Логотип фирмы Mishka"></li>
Аттрибуты высоты и ширины ты уже вполне можешь взять из макета

2020-09-21 06:38 UTC, costigans commented on css/style.css
> +}
Это не полный набор свойств для корректного «visually-hidden»
Попробуй самостоятельно зугуглить полный

2020-09-21 07:03 UTC, costigans requested changes

2020-09-21 07:03 UTC, costigans commented on catalog.html
> +				<button class="button-page" type="button">Следующая</button>
Что означают «1, 2, 3, Следующая»?

2020-09-21 07:03 UTC, costigans commented on catalog.html
> +				<p class="contacts-box__text">
Подбери более подходящий тег

2020-09-21 07:03 UTC, costigans commented on catalog.html
> +					тел.<a href="tel:+78122757575"></a>+7 (812) 275-75-75
С этой ссылкой что-то случилось :)

2020-09-21 07:03 UTC, costigans commented on catalog.html
> +				<!-- я правильно  -->
Что?)

2020-09-21 12:04 UTC, buxpob commented on index.html
> +<body class="page-bady">
Исправил

2020-09-21 12:05 UTC, buxpob commented on index.html
> +				<li class="service__item">
Исправил

2020-09-21 12:07 UTC, buxpob commented on index.html
> +				<li class="service__item">
Исправил

2020-09-21 13:12 UTC, buxpob commented on catalog.html
> +				<button class="button-page" type="button">Следующая</button>
ну судя по всему это номера страниц

2020-09-21 13:16 UTC, buxpob commented on index.html
> +					<li class="indicators-list__item">
исправил

2020-09-21 13:17 UTC, buxpob commented on index.html
> +						<p class="indicators__info">50<span class="indicators-item__info_little">%</span></p>
исправил

2020-09-21 13:21 UTC, buxpob commented on css/style.css
> +}
нашёл, исправил

2020-09-21 13:28 UTC, buxpob commented on index.html
> +				<li><a class="manufacturers__link" href="#">Mishka</a><img src="#" alt="Логотип фирмы Mishka"></li>
сделал

2020-09-21 13:29 UTC, buxpob commented on catalog.html
> +					<li><a class="site-navigation__link navigation-item" href="catalog.html">Магазин</a></li>
ок

2020-09-21 13:29 UTC, buxpob commented on catalog.html
> +					<li><a class="site-navigation__link navigation-item" href="#">Студия</a></li>
исправил

2020-09-21 13:29 UTC, buxpob commented on catalog.html
> +						<img src="#" alt="Шаблон сайта «Sedona»">
готово

2020-09-21 13:31 UTC, buxpob commented on catalog.html
> +						<div class="template-item__path"></div>
судя по Слайдгайду, над картинкой есть какой-то элемент, вот это он и есть. Я думал сделать это фоном, но из-за того, что у нас все цвета в :root, не представляю как сделать прозрачным только фон. Я делаю прозрачность для тега li и картинка у меня тоже становится полупрозрачной

2020-09-21 13:31 UTC, buxpob commented on catalog.html
> +				<p class="contacts-box__text">
ок

2020-09-21 13:31 UTC, buxpob commented on catalog.html
> +					тел.<a href="tel:+78122757575"></a>+7 (812) 275-75-75
исправил

2020-09-21 13:32 UTC, buxpob commented on catalog.html
> +				<!-- я правильно  -->
хотел написать коммент, передумал))

2020-09-22 03:50 UTC, costigans requested changes
Не нужно задавать вопросы и давать пояснения комментариями в коде, это анти-практика.
Используй возможности сервиса, пиши так же как и я — используя интерфейс Гитхаба.
Это тебе пригодится в будущем :)

2020-09-22 03:50 UTC, costigans commented on catalog.html
> +						<div class="template-item-path"></div>
Для каких целей служит этот `div`?

2020-09-22 03:50 UTC, costigans commented on catalog.html
> +					<!-- судя по всему это номера страниц,  -->
Судя по всему да, а представь как это можно понять со скринридера?
Чего не зватает?

2020-09-22 03:50 UTC, costigans commented on index.html
>  			<!-- можно так классы назвать или лучше не надо, что бы не запутаться? -->
«Так» это как?

2020-09-22 03:50 UTC, costigans commented on index.html
>  			<!-- Я правильно понимаю, что потом я просто буду при клике на кнопку делать некоторые дивы невидимыми, если да, то можно ли сделать такие классы, в смысле такие же, но с добавлением номера слайда
Можно использовать сложные селекторы (`nth-child` и т.п.), это избавит от необходимости плодить лишние классы.

2020-09-22 03:50 UTC, costigans commented on index.html
>  				<!-- по БЭМ например параграфы нужно делать элементами или блоками, честно говоря не совсем понимаю как лучше -->
Не думай сейчас про БЭМ. На данном этапе он будет вредным помощником.

2020-09-22 03:50 UTC, costigans commented on index.html
> +					тел.<a href="tel:+78122757575">+7 (812) 275-75-75</a>
Номер телефона разве является частью адреса?

2020-09-22 07:55 UTC, buxpob commented on catalog.html
> +						<div class="template-item-path"></div>
при наведении на карточку товара должна появляться доп информация и меняться цвет вот этого элемента, вот это и есть див. Я хотел сделать это в виде фона, но судя по слайдгайду это не фон. И даже если бы я хотел сделать это в виде фона, то из-за того, что все цвета должны содержаться в :root, я не представляю как это можно сделать. При подключении на прямую цвета, я бы просто сделал, что при наведении на li, background-color: opacity 1. я через рут я не знаю как сделать
![Без имени](https://user-images.githubusercontent.com/60325786/93856409-ab3cd600-fcc1-11ea-9182-5d1fbeb44281.png)

2020-09-22 08:01 UTC, buxpob commented on catalog.html
> +					<!-- судя по всему это номера страниц,  -->
думаю, что можно добавить спан с текстом страница и сделать его невидимым

2020-09-22 08:03 UTC, buxpob commented on index.html
>  			<!-- можно так классы назвать или лучше не надо, что бы не запутаться? -->
дать всем дивам общий класс slide и каждому ещё slide1, slide2 и так далее

2020-09-22 08:05 UTC, buxpob commented on index.html
>  			<!-- Я правильно понимаю, что потом я просто буду при клике на кнопку делать некоторые дивы невидимыми, если да, то можно ли сделать такие классы, в смысле такие же, но с добавлением номера слайда
учту

2020-09-22 08:06 UTC, buxpob commented on index.html
>  				<!-- по БЭМ например параграфы нужно делать элементами или блоками, честно говоря не совсем понимаю как лучше -->
хорошо

2020-09-22 08:13 UTC, buxpob commented on index.html
> +					тел.<a href="tel:+78122757575">+7 (812) 275-75-75</a>
исправил

2020-09-22 08:29 UTC, costigans commented on catalog.html
> +					<!-- судя по всему это номера страниц,  -->
Можно перед списком добавить одну строчку что-то вроде «Список страниц»

2020-09-22 08:32 UTC, costigans commented on index.html
>  			<!-- можно так классы назвать или лучше не надо, что бы не запутаться? -->
Смотря для каких целей это использовать. Если просто для стилизации, то как писал раньше — используй сложные селекторы. Если нужна «привязка» к слайдом для оживления JS, то для этой цели лучше подойдёт `id`.

2020-09-22 08:32 UTC, buxpob commented on index.html
>  			<!-- Я правильно понимаю, что потом я просто буду при клике на кнопку делать некоторые дивы невидимыми, если да, то можно ли сделать такие классы, в смысле такие же, но с добавлением номера слайда
вот в данном случае мне лучше не задавать классы, а например сделать правила в css через селектор так?

.slide {....}
.slide nth-child(1) {...}
.slide nth-child(2) {...}
.slide-button

![Без имени](https://user-images.githubusercontent.com/60325786/93859881-e1c91f80-fcc6-11ea-91fd-62355f15dbb9.png)

2020-09-23 07:15 UTC, buxpob commented on catalog.html
> +						<div class="template-item-path"></div>
хотя наверно можно просто убрать прозрачность у фона?

2020-09-23 07:23 UTC, costigans commented on index.html
>  			<!-- Я правильно понимаю, что потом я просто буду при клике на кнопку делать некоторые дивы невидимыми, если да, то можно ли сделать такие классы, в смысле такие же, но с добавлением номера слайда
Когда я отвечал, я в голове представлял блоки под слайдом (желтый/красный/зелёный) :)
В случае слайда тебе по сути нужен только один вспомогательный класс — он делает слайд видимым, а остальные скрытые (состояние по умолчанию).

2020-09-23 07:23 UTC, costigans commented on catalog.html
> +						<div class="template-item-path"></div>
Это декоративный (оформительский) элемент, который не несёт никакой информации, а лишь «украшает».
Теги существуют для придания информации смысла, чтобы браузеры/поисковики/другие потребители информации понимали конченое назначение сочетаний букв :)

2020-09-23 07:23 UTC, costigans commented on catalog.html
> +						<div class="template-item-path"></div>
Декоративные элементы мы добавляем с помощью стилей.
Так что тебе придётся удалить все эти пустые `div`'ы

2020-09-24 09:59 UTC, costigans approved these changes

2020-09-24 09:59 UTC, costigans commented on catalog.html
> +					<li><a class="catalog-page" href="#">Магазин</a></li>
Лучше всё же `active-page`, и убрать `href`

2020-09-24 09:59 UTC, merged