сетка
htmlacademy-htmlcss/1350493-nerds-29 pull request #6
Opened 2020-10-14 18:35 UTC by buxpob

2020-10-16 12:26 UTC, costigans requested changes

2020-10-16 12:26 UTC, costigans commented on css/style.css
> +	background-image: url(../img/index-slide1.png);
Не забывай про кавычки
`background-image: url("../img/index-slide1.png");`

2020-10-16 12:26 UTC, costigans commented on index.html
> +				<div class="slide slide2 visually-hidden">
Зачем тебе `slide2` `slide3`?
Используй псевдокласс `:nth-child(...)`

2020-10-16 12:26 UTC, costigans commented on index.html
> +				<div class="slide slide2 visually-hidden">
`visually-hidden` здесь не к месту.
Нам нужно полностью скрывать — `display:none`

2020-10-18 08:26 UTC, buxpob commented on catalog.html
> +		<div class="catalog-main-wrapper container">
по сути одно и тоже, по container содержит свойства общие для центровки, а wrapper содержит grid свойства

2020-10-20 13:32 UTC, costigans commented on catalog.html
> +		<div class="catalog-main-wrapper container">
Лучше назвать по-другому, можешь оставить просто `catalog-main'?

2020-10-20 13:50 UTC, costigans requested changes

2020-10-20 13:50 UTC, costigans commented on catalog.html
> +						191186, Санкт-Петербург,<br>ул. Б. Конюшенная, д. 19/8
А попробуй перенести текст только стилями — за счёт ширина блока `address`

2020-10-20 13:50 UTC, costigans commented on catalog.html
>  					Скидка 10% для друзей из социальных сетей.
Это предложение тоже можно обернуть в тег `p`, и можно спокойно избавиться от `<br>`

2020-10-20 13:50 UTC, costigans commented on css/style.css
> +	padding: 5px 22px 5px;
А что не так было с `padding: 5px 22px;`?

2020-10-20 13:50 UTC, costigans commented on css/style.css
> +.catalog-page {
У тебя стилизация активного пункта меню, а не пункта про магазин. Просто это состояние отрисовано на единственном макете внутренней страницы.
Можно использовать класс `active`:
`.site-navigation .current-link {...}`

2020-10-20 13:50 UTC, costigans commented on css/style.css
> +.catalog-page::before {
Почему выбрал такую реализацию, а не `border` например?

2020-10-20 13:50 UTC, costigans commented on css/style.css
> +.slides .slide:nth-child(2) {
Оберни слайды в список `slide-list`.
Сейчас `slide:nth-child(X)` запутывает, а потом будет 1 слайд — первый child и т.п.

2020-10-20 13:50 UTC, costigans commented on css/style.css
> +	background-position: 99% 0%;
Для чего такая «точечная» подстройка?

2020-10-20 13:50 UTC, costigans commented on css/style.css
> +	margin-bottom: -16px;
Выглядит грязно

2020-10-20 16:15 UTC, buxpob commented on css/style.css
> +.catalog-page::before {
У меня есть на ссылке padding, и если я сделаю бордер, то полоска будет шире, чем в макете

2020-10-20 16:25 UTC, buxpob commented on css/style.css
> +	background-position: 99% 0%;
Я всё ловлю пиксель пёрфект, но думаю что зря

2020-10-20 16:31 UTC, buxpob commented on css/style.css
> +	margin-bottom: -16px;
что именно, отрицательный margin?

2020-10-20 16:41 UTC, buxpob commented on css/style.css
> +	margin-bottom: -16px;
паддинг для того, что бы кусок фона был видел, а маргин отрицательный, т.к. у грида gap 40px, а нужно меньше, или как лучше сделать тогда

2020-10-21 01:17 UTC, costigans commented on css/style.css
> +	margin-bottom: -16px;
Лучше выбрать решение, которое не требует доработки напильником :)

2020-10-21 01:17 UTC, costigans commented on css/style.css
> +	background-position: 99% 0%;
Есть же допуски в критериях. Почитай

2020-10-21 01:18 UTC, costigans commented on css/style.css
> +.catalog-page::before {
Подумай, как это можно реализовать. Нужен ли в этом случае вообще паддинг?

2020-10-21 15:09 UTC, buxpob commented on css/style.css
> +.catalog-page::before {
Так можно и без паддинга, но я так понял, что будет лучше, если площать ссылки будет больше. Я могу li добавить паддинги, а ссылке бордер добавить и всё будет норм. Так и сделать?

2020-10-24 03:53 UTC, merged